version: "3"

services:
  db:
    image: mdillon/postgis
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
