# Generated by Django 2.1 on 2018-09-03 19:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dishwasher',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total area in square metres'),
        ),
    ]
