# Generated by Django 2.1 on 2018-09-03 18:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import aperol.properties.models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='AgencyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('would_recommend', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.City')),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LettingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property number or name', max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price', models.IntegerField(verbose_name='Total price per month')),
                ('deposit', models.IntegerField(null=True)),
                ('bedrooms', models.IntegerField()),
                ('double_bedrooms', models.IntegerField()),
                ('single_bedrooms', models.IntegerField()),
                ('total_area', models.IntegerField(null=True, verbose_name='Total area in square metres')),
                ('bathrooms', models.IntegerField()),
                ('ensuites', models.IntegerField()),
                ('furnished', models.BooleanField()),
                ('dishwasher', models.BooleanField()),
                ('bath', models.NullBooleanField()),
                ('shower', models.NullBooleanField()),
                ('garden', models.NullBooleanField()),
                ('dryer', models.NullBooleanField()),
                ('washing_machine', models.NullBooleanField()),
                ('microwave', models.NullBooleanField()),
                ('fridge', models.NullBooleanField()),
                ('freezer', models.NullBooleanField()),
                ('stove', models.NullBooleanField()),
                ('oven', models.NullBooleanField()),
                ('air_conditioning', models.NullBooleanField()),
                ('kitchen_table', models.NullBooleanField()),
                ('desks_in_rooms', models.NullBooleanField()),
                ('double_glazing', models.NullBooleanField()),
                ('bike_storage', models.NullBooleanField()),
                ('parking_space', models.NullBooleanField()),
                ('fire_alarm', models.NullBooleanField()),
                ('burglar_alarm', models.NullBooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.LettingAgency')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.CityArea')),
                ('landlord', models.ForeignKey(default=aperol.properties.models.get_blank_landlord, on_delete=django.db.models.deletion.CASCADE, to='properties.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('agency_photo', models.BooleanField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('would_recommend', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
