# Generated by Django 2.1 on 2018-09-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20180919_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propertyreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgencyReview',
        ),
        migrations.DeleteModel(
            name='PropertyReview',
        ),
    ]
