# Generated by Django 2.1 on 2018-09-25 08:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20180919_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddField(
            model_name='cityarea',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddField(
            model_name='lettingagency',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['street', 'pk']),
        ),
    ]
