# Generated by Django 2.1 on 2018-09-25 08:23

from django.db import migrations


def gen_slugs(apps, schema_editor):
    models = [
        apps.get_model('properties', 'City'),
        apps.get_model('properties', 'CityArea'),
        apps.get_model('properties', 'LettingAgency'),
        apps.get_model('properties', 'Property'),
    ]

    for model in models:
        for obj in model.objects.all():
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20180925_0814'),
    ]

    operations = [
        migrations.RunPython(
            gen_slugs, reverse_code=migrations.RunPython.noop),
    ]
