# Generated by Django 2.1 on 2018-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20180927_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityarea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
