# Generated by Django 2.1 on 2018-09-28 06:18

import aperol.properties.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_lease_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='variant',
            field=models.ForeignKey(default=aperol.properties.models.get_apartment_variant, on_delete=django.db.models.deletion.CASCADE, to='properties.PropertyVariant'),
        ),
        migrations.AlterField(
            model_name='propertyvariant',
            name='name',
            field=models.CharField(help_text='The variant name', max_length=50, unique=True),
        ),
    ]
