# Generated by Django 2.1 on 2018-09-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20180928_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='double_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='ensuites',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Minimum price per month per person'),
        ),
        migrations.AlterField(
            model_name='property',
            name='single_bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total area in square metres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='Total price per month for all tenants'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='lease_length',
        ),
        migrations.AddField(
            model_name='property',
            name='lease_length_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
