# Generated by Django 2.1 on 2018-10-17 13:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20180928_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLandmarkDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers between the property and landmark')),
                ('cycling_time', models.IntegerField(blank=True, help_text='Cycling time between property and landmark in minutes')),
                ('walking_time', models.IntegerField(blank=True, help_text='Walking time between property and landmark in minutes')),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Landmark')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='propertylandmarkdistance',
            unique_together={('property', 'landmark')},
        ),
    ]
