# Generated by Django 2.2.3 on 2019-07-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20181017_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='uploaded_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
